### ISSUE TITLE
大佬 求下PaddleOcr服务的接口处理代码

### ISSUE THREAD

**Issue by klockup** [WayJ/idcardocr#2]
谢谢~

**Comment by WayJ** [comment]
代码很简单，另外PaddleOcr也更新很多版本了，建议用新版本自己包装个接口，或者直接使用paddleocr的自带接口（如果有的话）

**Comment by WayJ** [comment]
找下了文档，没有自己额外写接口。
1、paddleocr 启动服务
2、paddleocr.py 文件中调用接口

其他相关文档贴一下


## 源码部署

### 1. 下载源码

git clone 或者直接下载压缩包，源码大小约 370MB

```shell
git xxxxx(自己找下paddleocr源码地址)
```

### 2. 快速启动服务

#### 2.1. 准备环境

```shell
# 安装paddlehub  
pip3 install paddlehub --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple
```


#### 2.2. 安装服务模块

```
hub install deploy/hubserving/ocr_system/
```

#### 2.3. 启动服务

```
hub serving start -m ocr_system --use_multiprocess
```

这样就完成了一个服务化API的部署，使用默认端口号8866

#### 2.4. 其他

* 本机测试 `python3 tools/test_hubserving.py http://127.0.0.1:8866/predict/ocr_system ./doc/imgs/123.jpg`
* 停止服务 `hub serving stop -p 8866`
* 卸载旧服务包 `hub uninstall ocr_system`
* 安装修改后的新服务包 `hub install deploy/hubserving/ocr_system/`
* 重新启动服务 `hub serving start -m ocr_system`
